### ISSUE TITLE
Add Python example

### ISSUE THREAD

**Issue by smalers** [OpenCDSS/cdss-rest-services-examples#2]
Need to add a Python example for real-time streamflow access.  This should be a simple program called `get-streamflow.py` that has the following elements.  **This issue can be split into separate issues by the developer.**

1. Main program entry point detected by checking for `__main__`.
2. `parse_command_line` function that handles the following arguments:
     1. `--stationid` for station identifier (abbreviation)
     2. `--ui` to run the UI (default is batch mode)
     3. `--output Filename` to specify the output filename (default is stdout).
3. Default will be to query the station telemetry time series for the given `stationid` and output to CSV format.
4. Create main run functions:
    1. `run_batch` to run in batch mode.  Use `urllib`? to get the content from the URL and save to file.
    2. `run_ui` to run in UI mode.  Implement a simple Qt interface that allows entering the station ID (abbrev), gets the data, and does a simple time series graph.
5. For simplicity, maybe put all the code in one file, even if classes are used.   Want to make it as easy as possible for someone to download and run the example.

**Comment by Nightsphere** [comment]
Python example created and pushed!
