### ISSUE TITLE
Feedback on JavaScript example

### ISSUE THREAD

**Issue by smalers** [OpenCDSS/cdss-rest-services-examples#3]
Here is my feedback on the JavaScript examples.  This issue can be used for a branch number or split into other issues.

1. The `README.md` file needs to be completed similar to other technologies.   This is the first thing that I read when reviewing and the current file is sparse.  I'm going to do my best.  For example, the README should provide a summary of folders and files and explain how to run the examples, such as opening the `index.html` file in a web browser.  A list of js files would be helpful since `npm` is not used because the developer will need to manage dependencies themselves, right?

2. Are there going to be separate examples for telemetry station real-time data and other data?  If so, maybe the files should be name `index-telemetry-station-15min.html`, etc.   It should be easy for someone to understand what files they need to use should they want to copy the examples for their own use.

3. At OWF we typically create separate folders named `css/` (CSS) and `js` (javascript), and if there were data use `data/`.   The README can list the files so it is clear what is a third-party library and application code.

4. The README file should also discuss key topics like how JavaScript provided by the State is used, how paging is handled, api key, and handling of missing data.  For example, include some notes in the README that describes which functions are used, etc.

5. I ran the example by opening the `index.html` file in Chrome wit `Ctrl-o`.  The demonstration came up fine.  I did not run the server.  Explain in the README why the server is needed.

6. Be consistent in date/time handling.
       1. The "Apr 2019", etc. is OK for a general graph.  As indicated in extensive internal discussion, the format may need to change if zooming is provided, but don't need to solve all those issues now.
  1. Date/time format should be `YYYY-MM-DD hh:mm` for easiest viewing.  Programmers can use their own formats if they want to change.  The use of "T" in the string is OK internally but that is probably a visual distraction to most users.
  2. Showing time zone for visual displays can also be distracting so I recommend removing for general display.  In the README and code can note that data values are returned in local time zone.   You will see the impact of this when daylight savings time changes.  For example, in the spring (this weekend actually, "spring forward" results in a gap Sunday March 8 at 2AM.
  3. Pop-up time should also be consistent, although user experience is important.  The approach taken is not too bad, but don't display seconds.  If trying to be consistent with the table, use ISO time format that is similar so it is easy to compare, for example use 24 hour time in both rather than am/pm in popup.

7. Make the introduction more specific and concise.  "This example illustrates how to retrieve and display real-time (15 minute) streamflow data."  I recommend that you leave the technical discussion about div, etc. in the README and use formatting to be more clear, for example, `<div>`.

8. As previously discussed, handle missing data by showing as a gap in the graph and empty rows in the table.  The README should explain that the web services only return non-missing values and the consuming application must therefore handle appropriately.  For real-time data for a short display period, using points (symbols only) is an effective technique for not having to deal with gaps.

9. Follow general rules when formatting data in tables:
  1. Strings are left-justified.
  2. Dates are left-justified.
  3. Numbers are right-justified and should align at the decimal point if present.   This can get tricky if formatting as a string before display but ideally the tool can display numbers right justified.

10. Table scrollbar causes heading to not align.  This seems to be a common issue for scrolling tools.  The separator line  between headings should always align with separator for data rows, regardless of how large the table.  The tool should either handle this itself or something may need to be done to insert something above the scrollbar in heading area.  Talk to Catherine.

11. Does the table have an option to allow users to indicate sort order?  That would be nice.

12. The location of the data needs to be indicated somewhere.  Change the title of the graph to "ABBREV - Station Name" so it would be something like "PLAKERCO - SOUTH PLATTE RIVER NEAR KERSEY, CO".

13. Be consistent for data type (parameter) and units.
  1. Y-axis title is fine.
  2. Legend is OK but change to "DISCHRG (CFS)".  However, this design breaks down when two time series are on the same graph, in which case legend format similar to TSTool is needed to differentiate lines.  Stick with one time series for the example so we can close this work out.
  3. Same goes for the table heading.  For one time series "DISCHRG (CFS)" is enough and if multiple time series were listed in the same table it would need to be something like "PLAKERCO, DISCHRG (CFS)".
  4. Hopefully the data type, units, station name, etc. are retrieved from the data and not hard-coded.

14.  The pop-up is a little confusing.  Why a square with transparent pink/red whereas the legend uses not-transparent pink/red?

16. If `npm` is used to download packages and manage dependencies, describe this in the README and use a script to run npm, even if a one-liner. 

17. `style.css` file needs at least minimal comments.

18. Add sections to the README about the main packages used, in particular chart.js and clusterize.js explaining basic configuration.   This will help people that want to use their own components, and also help OWF staff.

19.  Comments on index.html are in red-lined hard-copy.

**Comment by Nightsphere** [comment]
All major issues taken care of in this issue. I'm closing this one and moving the 3 unfinished smaller things into another low priority issue
