### ISSUE TITLE
Need more javascript examples

### ISSUE THREAD

**Issue by smalers** [OpenCDSS/cdss-rest-services-examples#4]
Once the telemetry station DISCHRG example is cleaned up, other examples should be created by copying that example and making minor changes, or maybe just have multiple sets of graph/table on the same page.  For example:

1. For telemetry station DISCHRG, use PLAKERCO.

2. Calls - use the calls query to show a point graph of when a call was made, with the y-axis value being the appropriation date  (number as YYYYMMDD) or administration number and need to indicate the WDID structure making the call (via popup?) - need to discuss.  This shows how often water is called for when the river is overappropriated.  It may make sense to use a heat map if we have budget.  In this case, there is no need to fill a time series because these values occur at irregular times.

3. Reservoir levels - need to pick a reservoir like Chatfield (CHARESCO) and parameter STORAGE.  Missing data handling will be similar to DISCHRG.

Whatever is done, the code needs to be understandable.

**Comment by Nightsphere** [comment]
Calls has not been implemented, but the other two have been. Moving Calls to another lower pressing issue
